name: combinator
version: 1.0.0
description: Packrat parser combinators that support static typing, generics, file spans, memoization, and more.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/combinator.git
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  code_buffer: ^1.0.0
  matcher: ^0.12.0
  source_span: ^1.0.0
  string_scanner: ^1.0.0
  tuple: ^1.0.0
dev_dependencies:
  dart2_constant: ^1.0.0
  t_stats: ^1.1.2
  test: ^0.12.0